export default {
	LINK: 'link',
	NAMESPACE: 'namespace',
	REQUIRED: 'required',
	SINGLETON: 'singleton',
	KEEPALIVE: 'keepalive',
	STATIC: 'static',
	MEMBER: 'member',
	RUNTIME: 'runtime',
	IMPORT: 'import',
	ASYNC: 'async',
	AS: 'as',
	FROM: 'from',
	COMMA: ',',
	STRING: /'(?:\\['\\]|[^\n'\\])*'/,
	LSQBRACKET: '[',
	RSQBRACKET: ']',
	LPAREN: '(',
	RPAREN: ')',
	SPREAD_OPERATOR: '...',
	DOTOP: '.',
	JS_BLOCK: /\[\[[^]*?\n\]\]$/,
	JS_BLOCK2: /{[^]*?\n}$/,
	IDENTIFIER: /[a-zA-Z][a-zA-Z0-9]*/,
	SPACE: { match: /\s+/, lineBreaks: true },
	SEMICOLON: ';'
};